config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get 'signup' , to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login' ,to:'sessions#create'
  delete 'logout' ,to:'sessions#destroy'
  
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end 
end

 

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence:true, length: {maximum: 50}
  
  validates :email, presence:true, length: {maximum:100},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness:true
                    
  has_secure_password
  validates :password, presence: true, length: {minimum:6 }, allow_nil:true
  
  validates :department, length:{in:2..30},allow_blank:true
  
  validates :basic_time, presence: true
  validates :work_time, presence:true
  
  
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  
  
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token=User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:edit,:update,:destroy,:edit_basic_info,:update_basic_info]
  before_action :logged_in_user,only:[:index,:show,:edit,:update,:destroy,:edit_basic_info,:update_basic_info]
  before_action :correct_user,only:[:edit,:update]
  before_action :admin_user,only:[:index,:destroy,:edit_basic_info,:update_basic_info]
  before_action :admin_or_correct_user,only: :show
  before_action :set_one_month,only: :show
  
  def index
    @users=User.paginate(page:params[:page],per_page:30)
    @users=@users.where('name LIKE?', "%#{params[:search]}%") if params[:search].present?
  end
    
  def show
    @worked_sum =@attendances.where.not(started_at:nil).count
  end
    
  def new
    if logged_in?
      flash[:info]="すでにログインしています"
      redirect_to current_user
    end
    @user=User.new
  end
  
  
  def create
   @user=User.new(user_params)
   if @user.save
     log_in @user
     flash[:success]='新規作成に成功しました。'
     redirect_to @user 
   else
     render :new
   end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
     flash[:success]="ユーザー情報を編集しました。"
     redirect_to @user
    else
     render :edit
    end
  end
  

  def destroy
    @user.destroy
    flash[:danger]="#{@user.name}を削除しました。"
    redirect_to users_url
  end
  
  
  #以下、基本情報系＃
  def edit_basic_info
  end
  
  
  def update_basic_info
    @users=User.all
      @users.each do |user|
        if user.update_attributes(basic_info_params)
          flash[:success]="全員の基本情報を更新しました。"
        else
          flash[:danger]="更新は失敗しました。<br>" + user.errors.full_messages.join("<br>")
        end
      end
      redirect_to users_url
  end
  
  
  
  
  private
  
    def user_params
      params.require(:user).permit(:name,:email, :password,:password_confirmation, :department)
    end
    
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour*60)+time.min)/60.0)
  end
  
  
end

app/views/users/_form.html.erb
<%= form_with(model:@user, local:true ) do |f|  %>
  <%=render 'shared/error_messages' , object:f.object%>
  
  <%=f.label :name ,class: "label-#{yield(:class_text)} label-form" %>
  <%=f.text_field :name ,class:"form-control" %>
  
  <%=f.label :email ,class: "label-#{yield(:class_text)} label-form"%>
  <%=f.email_field :email ,class:"form-control" %>
  
  <%=f.label :department, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.text_field :department, class:"form-control" %>
  
  <%=f.label :password, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.password_field :password, class:"form-control"%>
  
  <%=f.label :password_confirmation, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.password_field :password_confirmation, class:"form-control" %>
  
  
  <%=f.submit yield(:button_text), class:"btn btn-primary btn-block btn-#{yield(:class_text)} btn-form" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,@user.name) %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title,'edit_basic_info') %>
<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_with(model:@user, url:update_basic_info_user_path(current_user),method: :patch, local:true) do |f| %>
      <%= render 'shared/error_messages', object:@user %>
      
        <%= f.label :work_time, class: "label-form" %>
        <%= f.time_field :work_time , class: "form-control" %>
        
        <%= f.label :basic_time, class: "label-form" %>
        <%= f.time_field :basic_time, class: "form-control" %>
        
        <%= f.submit "編集", class:"btn btn-block btn-primary btn-form" %>
    <% end %>
    
     
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title,"Users") %>
<h1>利用者一覧</h1>
<div class="row">
  <div class="col-md-7">
    <table class="table table-hover" id="users-table">
    <%=will_paginate %>
      <thead>
       <tr>
         <th>名前</th>
       </tr>
      </thead>  
      
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%=link_to user.name ,user %> <span>|</span> <%=link_to "基本情報編集", edit_basic_info_user_path(user)%></span> 
          <% if ! user.admin? %>
            <span>|</span> <%=link_to "削除", user_path(user), method: :delete ,data:{confirm: "#{user.name}を削除します。よろしいですか？"} %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%=will_paginate %> 
  </div>
  
  <div class="col-md-4">
    <%= form_with(model:@user, url:users_path, method: :get, local:true) do |f| %>
      <p>ユーザー名を検索</P>
      <%=f.text_field:search, id:"search-form"%>
      <%=f.submit "検索", class:"btn btn-primary btn-sm btn-search" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title,"Sign up") %>
<% provide(:class_text,'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
    <table class="table table-bordered" id="user-info-table" >  <%# col-md　書いていない#%>
      <tbody>
        <tr>
          <td><%= link_to "←",user_path(date:@first_day.prev_month), class: "btn btn-primary btn-change" %><span class="time-board-title"><%= l(@first_day, format: :middle)%> 時間管理表</span><%= link_to "→",user_path(date:@first_day.next_month), class: "btn btn-primary btn-change" %></td>
          <td>指定時間  <%= format_basic_info(@user.work_time) %> </td>   <%# 月切り替えボタンの追加により、縦幅が拡大するため、隣のセルのvertical中央の基準が変化する。#%>
          <td colspan="3"><%= format_basic_info(@user.basic_time) %>  基本時間</td>　　　<%#　セルの幅の指定より先に結合を考える #%> 
          <td>初日  <%= l(@first_day, format: :short)%></td>
        </tr>
        <tr>
          <td style="width:45%">所属  <%= @user.department? ? @user.department : "未所属" %></td>
          <td style="width:22%">氏名  <%= @user.name %></td>
          <td style="width:5%">コード</td>
          <td style="width:1%"></td>
          <td style="width:14%">出勤日数  <%=@worked_sum %>日</td> <%#　入力した文字によって、セルの幅は自動調節してくれるので先に文字を入れてしまおう。その後、widthで微調整 #%>
          <td style="width:13%">締め  <%= l(@last_day, format: :short) %></td>
        </tr>　　
    </table>
    
    <div class="btn-wrapper" %>
      <%= link_to "勤怠を編集",attendances_edit_one_month_user_path(date:@first_day), class: "btn btn-primary btn-edit-one-month" %>
    </div>
    
    <table class="table table-bordered table-striped" id="user-attendance-table" >  <%# table-striped　はtheadには反映されていない？#%>
      <thead>
        <tr>
          <th rowspan="2" style="width:5%">日付</th>
          <th rowspan="2" style="width:5%">曜日</th>
          <th colspan="3" style="width:19%">出社</th>
          <th colspan="3" style="width:11%">退社</th>
          <th rowspan="2" style="width:13%">在社時間</th>
          <th rowspan="2" style="width:5%">備考</th>
          <th rowspan="2" style="width:12%">残業指示</th>　　　<%# 後でカラムとしてモデルに追加予定　#%>
          <th rowspan="2" style="width:30%">指示者</th>
        </tr>
        <tr>
          <th style="width:5%">時</th>
          <th style="width:5%">分</th>
          <th style="width:9%"></th>
          <th style="width:5%">時</th>
          <th style="width:5%">分</th>
          <th style="width:1%"></th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <% css_class=
            case $days_of_the_week[day.worked_on.wday]
              when'土'
                'text-primary'
              when'日'
                'text-danger'
            end 
          %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class="<%=css_class %>"><%=$days_of_the_week[day.worked_on.wday] %></td>
            <td><%=l(day.started_at, format: :hour) if day.started_at.present? %></td>  <%# 独自にformatを編集#%>
            <td><%=l(day.started_at.floor_to(15.minutes), format: :minute) if day.started_at.present? %></td>
            <td>
              <% if btn_text=attendance_state(day) %>
                <%= link_to "#{btn_text}",user_attendance_path(@user,day),method: :patch, class:"btn btn-primary btn-register" %>
              <% end %>
            </td>
            <td><%=l(day.finished_at,format: :hour) if day.finished_at.present? %></td>
            <td><%=l(day.finished_at.floor_to(15.minutes),format: :minute) if day.finished_at.present? %></td>
            <td></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%=str_times=working_times(day.started_at.floor_to(15.minutes),day.finished_at.floor_to(15.minutes)) %> 
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %>
            </td>
            <td><%= day.note %></td>
            <td><%= day.overwork_direction %></td>
            <td><%= day.overwork_director %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan="2"><%=format_basic_info(@user.work_time).to_f*@worked_sum %></td>
          <td></td>
          <td colspan="6"><%=format("%.2f", @total_working_times.to_f) %></td>
          <td></td>
          <td></td>
          <td>所属長承認</td>
        </tr>
      </tbody>
    </table>
</div>